[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kaitenzushi"
version = "0.0.1"
description = ""
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest==7.4.3",
]
